# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2197d175a3f73338b6bd49ab80c0f4d0977660e818fdd9111c74cf67e46e2390de86e153658247a99f6227ab11f1869df045cf83ce5369f28426a241a2aa43ca

test:
  secret_key_base: de5b57635058d8049b0649d6e728c8bb3a847c0cfe4e7fc6a1a0a9d1a48fa16c8339d6dda7b851a4c53a3b5a6b94f8269e1eb55e00e777f7d898a8a0d7090f71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
